schema_version = "1.0.0"

id = "blender2game4goblins"
version = "1.1.0"
name = "blender-2-game-engine-4-goblins"
tagline = "An auto glTF export tool for syncing Blender with game engines"
maintainer = "kimja"
type = "add-on"
website = "https://github.com/mariaheine/blender-2-game-engine-4-goblins"
tags = ["Import-Export", "User Interface", "Pipeline", "Game Engine"]
blender_version_min = "4.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

# [permissions]
files = "Exporting GLTF/FBX files to user-specified disk locations."