schema_version = "1.0.0"

id = "kimjas_blender_2_unity_fast"
version = "1.0.0"
name = "blender-2-unity-fast"
tagline = "An exportiong tool for rapid prototyping in Blender for Unity"
maintainer = "Maria Heine"
type = "add-on"
website = "https://github.com/mariaheine/blender-2-unity-fast"
tags = ["Import-Export", "User Interface", "Pipeline", "Game Engine"]
blender_version_min = "4.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

# [permissions]
files = "Exporting GLTF/FBX files to user-specified disk locations."